

logging:
  level:
    root: warn

server:
  port: 8443
  ssl:
    key-store: classpath:keystore.jks
    key-store-type: JKS
    key-alias: localhost
    key-password: 1

spring:
  datasource:
    url: jdbc:mysql:manga-comics-db
    driver-class-name: com.mysql.jdbc.Driver
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: false # Disable h2 console
  main:
    banner-mode: off # Disable 'SPRING' banner when app starts
