logging:
  level:
    root: info # Show 'info' level logs (may change to 'debug')

spring:
  thymeleaf:
    cache: false

  datasource:
    url: jdbc:h2:file:~/manga-db-dev
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update # Update schema if necessary
    show-sql: true # Show SQL in logs
  h2:
    console:
      enabled: true # Enable h2 console