

logging:
  level:
    root: warn

server:
  port: 8443
  ssl:
    key-store: classpath:keystore.jks
    key-store-type: JKS
    key-alias: localhost
    key-password: 1

spring:
  datasource:
    url: jdbc:h2:file:~/manga-db-prod
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: false # Disable h2 console
  main:
    banner-mode: off # Disable 'SPRING' banner when app starts
