spring:
  application:
    name: application-with-monitoring (dev)

logging:
  level:
    root: info
    com.example.application_with_monitoring: debug

management:
  # All Endpoints
  endpoints:
    web:
      exposure:
        include: "*"
  # Configuring Endpoints
  endpoint:
    health:
      show-components: always
      show-details: always
    env:
      show-values: always
  info:
    env:
      enabled: true
    os:
      enabled: true
    java:
      enabled: true
    ssl:
      enabled: true
    process:
      enabled: true
    build:
      enabled: true
    git:
      enabled: true
      mode: simple