INSERT INTO TOPICS (TITLE, TEXT, CREATE_TIME, LIKES)
VALUES ('Work-Life Balance',
        'Finding a harmonious balance between professional responsibilities and personal life is key to long-term happiness. Explore strategies for managing time effectively, setting boundaries, and ensuring that work does not overwhelm your personal life, promoting mental well-being and productivity.',
        '2024-02-15 08:30:12', 45),
       ('Healthy Eating',
        'Nutrition is fundamental to overall health. Discover the importance of balanced meals, the benefits of whole foods, and how eating a variety of nutrient-dense foods can improve energy levels, immunity, and mental clarity. Learn simple tips to make healthier choices in daily life.',
        '2023-11-22 14:45:30', 103),
       ('Financial Planning',
        'Financial security is achieved through smart planning. Learn how budgeting, saving, and investing wisely can pave the way to a secure future. Explore retirement planning, emergency funds, and methods to maximize your financial growth for peace of mind and future stability.',
        '2024-01-10 09:15:05', 67),
       ('Daily Exercise',
        'Regular physical activity is key to maintaining optimal health. Understand the benefits of daily exercise, including weight management, stress reduction, and increased stamina. Learn how to incorporate exercise into your busy routine, from quick workouts to long-term fitness goals.',
        '2023-09-18 17:20:40', 82),
       ('Effective Communication',
        'Communication is not just about speaking—it’s about understanding. Dive into the importance of active listening, clear expression, and non-verbal cues in improving interpersonal interactions. Master the art of conveying ideas and building strong relationships both personally and professionally.',
        '2024-03-01 12:10:22', 123),
       ('Time Management',
        'Mastering time management can drastically improve productivity and reduce stress. Learn strategies for prioritizing tasks, setting realistic goals, and using tools like to-do lists and scheduling apps to stay organized. Discover how to overcome procrastination and make the most of your time.',
        '2023-10-05 07:55:33', 94),
       ('Mental Well-being',
        'Mental health is just as important as physical health. Explore practices like mindfulness, meditation, and self-compassion to boost emotional resilience. Learn how self-care habits, seeking support, and positive thinking can help manage stress and foster a balanced life.',
        '2024-02-28 18:30:10', 65),
       ('Sustainable Living',
        'Living sustainably reduces our environmental impact and conserves resources for future generations. Learn practical steps for reducing waste, conserving energy, and making eco-friendly choices in daily life. Explore sustainable alternatives in everything from transportation to home goods.',
        '2023-12-12 13:05:55', 41),
       ('Remote Work',
        'Remote work is changing the landscape of employment. Delve into the benefits and challenges of working from home, such as flexible hours, reduced commuting, and improved work-life balance, as well as strategies for staying focused, avoiding burnout, and maintaining collaboration remotely.',
        '2024-01-25 16:42:18', 109),
       ('Digital Privacy',
        'In the digital age, protecting personal information is more important than ever. Understand the risks of online data breaches and how to safeguard your privacy with strong passwords, encryption, and careful data sharing. Learn how to stay safe while using social media, emails, and online services.',
        '2023-08-30 10:22:37', 130),
       ('Parenting Tips',
        'Parenting is one of the most rewarding yet challenging experiences. Discover tips for nurturing children’s emotional, social, and cognitive growth. Explore how positive reinforcement, setting boundaries, and fostering open communication can create a healthy and supportive family environment.',
        '2024-03-03 20:15:47', 88),
       ('Public Speaking',
        'Overcoming the fear of speaking in front of others is an invaluable skill. Learn how to prepare impactful presentations, engage your audience, and project confidence, whether in a meeting, speech, or public event. Develop techniques for handling anxiety and speaking with clarity and conviction.',
        '2023-07-14 09:50:29', 75),
       ('Travel Budgeting',
        'Traveling doesn’t have to break the bank. Learn how to plan trips on a budget by finding affordable accommodations, cheap flights, and ways to save on food and activities. Discover money-saving tips to make your travel experiences unforgettable without the financial stress.',
        '2024-02-05 11:12:05', 56),
       ('Home Organization',
        'A clutter-free home promotes a calm and productive environment. Explore tips for decluttering spaces, organizing belongings, and optimizing your living area for efficiency. Learn simple and cost-effective methods to keep your home organized, from decluttering rooms to organizing storage spaces.',
        '2023-11-28 15:37:50', 102),
       ('Job Interviews',
        'Nailing a job interview requires preparation, confidence, and clear communication. Learn strategies for researching the company, answering common questions, and presenting your strengths in a compelling way. Get tips for handling nerves and making a great impression in any interview setting.',
        '2024-01-17 08:05:21', 67),
       ('Car Maintenance',
        'Proper car care ensures your vehicle runs smoothly for years. Learn essential car maintenance tips such as checking tire pressure, oil changes, and brake checks. Discover how simple, regular maintenance can prevent costly repairs and keep your car running efficiently.',
        '2023-09-25 14:55:09', 48),
       ('Healthy Relationships',
        'Strong relationships are built on trust, communication, and mutual respect. Learn how to nurture relationships with partners, family, friends, and colleagues. Discover strategies for resolving conflicts, improving emotional connections, and creating a supportive network of people who enrich your life.',
        '2024-02-10 19:20:33', 155),
       ('Saving Money',
        'Being mindful of expenses can lead to significant savings over time. Learn how to identify unnecessary spending, set savings goals, and make smarter financial decisions. Explore tips for budgeting, using coupons, and automating savings to improve your financial future.',
        '2023-10-22 06:40:15', 112),
       ('Productivity Hacks',
        'Simple changes to your routine can boost your productivity. Discover effective hacks like the Pomodoro technique, time-blocking, and task batching. Learn how to eliminate distractions, maintain focus, and optimize your environment for peak performance in both personal and professional tasks.',
        '2024-03-04 13:55:27', 120),
       ('Social Media Detox',
        'Constant use of social media can contribute to stress and anxiety. Discover the benefits of taking a break from screens to reset your mental health. Learn strategies to manage screen time and set boundaries, allowing more time for real-world connections, relaxation, and mindfulness.',
        '2023-08-19 21:10:42', 80),
       ('Cybersecurity Awareness',
        'Understanding cybersecurity risks is essential in today''s digital world. Learn how to protect personal and professional data, recognize phishing attempts, and implement best security practices to stay safe online.',
        '2024-02-20 10:30:45', 89),
       ('AI and Automation',
        'Artificial Intelligence and automation are transforming industries. Explore how businesses leverage AI to enhance productivity, streamline operations, and improve customer experiences.',
        '2023-12-01 14:15:33', 76),
       ('Personal Finance Tips',
        'Managing personal finances wisely can lead to long-term financial stability. Discover budgeting techniques, debt management strategies, and investment tips for a secure financial future.',
        '2024-01-05 08:45:12', 92),
       ('Mental Resilience',
        'Building mental resilience helps individuals navigate stress and adversity. Learn techniques such as mindfulness, gratitude, and self-care to develop a strong and healthy mindset.',
        '2023-11-15 17:10:20', 63),
       ('Tech Innovations',
        'Stay updated with the latest technological advancements, from quantum computing to biotech. Discover how emerging technologies are shaping the future and what opportunities they present.',
        '2024-03-10 12:50:55', 105);

INSERT INTO COMMENTS (TEXT, CREATE_TIME, LIKES, AUTHOR, TOPIC_ID)
VALUES ('Great tips on managing work and personal life! Definitely need to set better boundaries.',
        '2024-02-15 09:00:00', 10, 'John Doe', 1),
       ('This is something I struggle with, but these strategies make sense. Going to try them out!',
        '2024-02-15 09:15:22', 8, 'Will Smith', 1),
       ('Eating a balanced meal has made a big difference in my energy levels. Thanks for the great advice!',
        '2023-11-22 15:00:10', 15, 'Emily Clark', 2),
       ('I didn’t know whole foods could have such an impact on mental clarity. I’ll definitely make healthier choices now!',
        '2023-11-22 15:30:50', 12, 'Michael Lee', 2),
       ('This is exactly what I needed to read! Budgeting has always been a challenge for me.', '2024-01-10 09:45:00',
        14, 'Sarah Brown', 3),
       ('I’m going to start saving more for retirement. Great tips on how to get started!', '2024-01-10 10:00:30', 18,
        'David Harris', 3),
       ('I love that you mentioned quick workouts. Sometimes I just can’t find the time for long ones.',
        '2023-09-18 18:00:12', 11, 'Sophie Green', 4),
       ('Exercise is such an important part of life. I’ll be setting fitness goals now!', '2023-09-18 18:20:45', 9,
        'Andrew White', 4),
       ('Active listening really does make a difference in conversations. Thanks for the reminder!',
        '2024-03-01 13:00:00', 17, 'Liam Scott', 5),
       ('I’ve been trying to improve my communication at work, this advice is really helpful!', '2024-03-01 13:45:18',
        13, 'Ava King', 5),
       ('Time-blocking has changed my work-life balance! Thanks for the suggestion!', '2023-10-05 08:05:00', 16,
        'James Walker', 6),
       ('Overcoming procrastination is still a challenge for me, but I’m going to try these tips.',
        '2023-10-05 08:30:30', 14, 'Isabella Young', 6),
       ('Mindfulness has definitely helped me reduce stress. I recommend it to everyone!', '2024-02-28 19:00:25', 19,
        'Henry Adams', 7),
       ('Self-care is so important, but it’s easy to forget. Thanks for the great advice!', '2024-02-28 19:20:11', 16,
        'Olivia Baker', 7),
       ('I’ve been trying to reduce waste at home. These tips are really helpful.', '2023-12-12 14:00:00', 10,
        'Elijah Martin', 8),
       ('I need to be more eco-conscious in my daily choices. Going to make a change!', '2023-12-12 14:25:47', 12,
        'Chloe Davis', 8),
       ('Working remotely has its challenges, but I love the flexibility. Great tips here!', '2024-01-25 17:00:12', 20,
        'Lucas Taylor', 9),
       ('Remote work burnout is real. These strategies are definitely going to help me stay focused.',
        '2024-01-25 17:35:55', 22, 'Mia Harris', 9),
       ('I always forget about encryption. Thanks for the reminder to stay safe online!', '2023-08-30 10:45:20', 25,
        'William Wilson', 10),
       ('Great tips! I’m going to change my passwords and be more careful online.', '2023-08-30 11:05:33', 18,
        'Sophia Moore', 10),
       ('I needed these tips for my toddler. Communication is key!', '2024-03-03 21:00:10', 8, 'Charlotte Taylor', 11),
       ('Positive reinforcement works wonders. I’ll definitely use these tips in my parenting.', '2024-03-03 21:30:20',
        11, 'Benjamin Lee', 11),
       ('I get so nervous before speaking. These tips will help me manage my anxiety.', '2023-07-14 10:00:00', 6,
        'Ethan Clark', 12),
       ('I never considered using non-verbal cues. This is a great approach!', '2023-07-14 10:25:45', 5,
        'Amelia Martin', 12),
       ('I’ll be using these tips for my next trip. Budgeting is key to having a great experience!',
        '2024-02-05 12:00:00', 10, 'Mason Scott', 13),
       ('Affordable accommodations make a huge difference. Great travel tips!', '2024-02-05 12:45:30', 8,
        'Harper Davis', 13),
       ('I’ve been decluttering all month. These tips will help me stay on track.', '2023-11-28 16:00:15', 14,
        'Zoe Roberts', 14),
       ('Organizing my home has improved my productivity so much. Thank you for the advice!', '2023-11-28 16:30:55', 16,
        'Jack Wilson', 14),
       ('I always struggle with interviews. These tips will definitely help me prepare better.', '2024-01-17 09:15:00',
        12, 'Daniel Harris', 15),
       ('Researching the company is key! I’ll start doing that for my next interview.', '2024-01-17 09:40:20', 9,
        'Ella Lee', 15),
       ('Simple car maintenance really does save money. I’ll check my tire pressure this weekend.',
        '2023-09-25 15:00:10', 7, 'Lily Lewis', 16),
       ('I didn’t know regular oil changes were so important. Thanks for the tip!', '2023-09-25 15:30:55', 5,
        'Nathan White', 16),
       ('Trust and communication are key to any relationship. These tips are spot on!', '2024-02-10 20:30:40', 25,
        'Oliver Young', 17),
       ('Building stronger relationships takes work, but these strategies are definitely worth it.',
        '2024-02-10 21:00:00', 22, 'Amelia Taylor', 17),
       ('I’m definitely going to try automating my savings. Great idea!', '2023-10-10 12:30:25', 18, 'Matthew Moore',
        18),
       ('Cutting out unnecessary subscriptions is such an easy win. Thanks for the tip!', '2023-10-10 12:45:15', 14,
        'Aiden Garcia', 18),
       ('Mindful eating has helped me enjoy my meals more. I’m going to continue practicing this.',
        '2024-03-02 18:20:00', 10, 'Sophia Evans', 19),
       ('Being more conscious about my food choices has helped me feel better physically.', '2024-03-02 18:40:45', 11,
        'Ethan Thomas', 19),
       ('A digital detox is exactly what I need! Time to unplug for a while.', '2023-12-05 11:20:50', 19, 'Mia Clark',
        20),
       ('I’m going to try a digital detox this weekend. Can’t wait to disconnect!', '2023-12-05 11:45:30', 15,
        'Jacob Wilson', 20),
       ('Cybersecurity is more important than ever. Thanks for the great tips!',
        '2024-02-20 11:00:00', 12, 'Alice Johnson', 21),
       ('I fell for a phishing scam once. This article is a great reminder to stay vigilant.',
        '2024-02-20 11:30:10', 9, 'Mark Davis', 21),
       ('AI is revolutionizing so many industries. Exciting times ahead!',
        '2023-12-01 14:45:22', 15, 'John Carter', 22),
       ('Automation saves so much time, but I worry about job displacement.',
        '2023-12-01 15:10:45', 13, 'Emily Thompson', 22),
       ('Budgeting has helped me save so much money. Highly recommend tracking expenses.',
        '2024-01-05 09:15:30', 18, 'David Smith', 23),
       ('Investing early is key. Great insights in this topic!',
        '2024-01-05 09:45:12', 14, 'Olivia Brown', 23),
       ('Mental resilience is underrated. These strategies really help during tough times.',
        '2023-11-15 17:45:00', 11, 'Sophia Miller', 24),
       ('Gratitude journaling changed my life. Highly recommend!',
        '2023-11-15 18:10:22', 10, 'Ethan Wilson', 24),
       ('Quantum computing is fascinating! Can''t wait to see its real-world applications.',
        '2024-03-10 13:20:30', 20, 'Lucas Parker', 25),
       ('Keeping up with tech innovations is a challenge, but this article helps a lot.',
        '2024-03-10 13:50:40', 17, 'Ava Reed', 25);


INSERT INTO COMMENTS (TEXT, CREATE_TIME, LIKES, AUTHOR, TOPIC_ID)
VALUES ('I like what you think.',
        '2024-02-15 09:20:22', 2, 'Jane Smith', 1);