server:
  port: 8443
  ssl:
    key-store: classpath:keystore.jks
    key-store-type: JKS
    key-alias: localhost
    key-password: 1
spring:
  application:
    name: secured-web-app
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:h2:mem:blogium-db
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always