INSERT INTO GENRES (ID, NAME) VALUES (1, 'Action');
INSERT INTO GENRES (ID, NAME) VALUES (2, 'Comedy');
INSERT INTO GENRES (ID, NAME) VALUES (3, 'Drama');
INSERT INTO GENRES (ID, NAME) VALUES (4, 'Fantasy');
INSERT INTO GENRES (ID, NAME) VALUES (5, 'Horror');
INSERT INTO GENRES (ID, NAME) VALUES (6, 'Romance');
INSERT INTO GENRES (ID, NAME) VALUES (7, 'Sci-Fi');
INSERT INTO GENRES (ID, NAME) VALUES (8, 'Thriller');
INSERT INTO GENRES (ID, NAME) VALUES (9, 'Adventure');
INSERT INTO GENRES (ID, NAME) VALUES (10, 'Mystery');
INSERT INTO GENRES (ID, NAME) VALUES (11, 'Animation');
INSERT INTO GENRES (ID, NAME) VALUES (12, 'Documentary');
INSERT INTO GENRES (ID, NAME) VALUES (13, 'Biography');
INSERT INTO GENRES (ID, NAME) VALUES (14, 'Musical');
INSERT INTO GENRES (ID, NAME) VALUES (15, 'Western');
INSERT INTO GENRES (ID, NAME) VALUES (16, 'Historical');
INSERT INTO GENRES (ID, NAME) VALUES (17, 'Crime');
INSERT INTO GENRES (ID, NAME) VALUES (18, 'Family');
INSERT INTO GENRES (ID, NAME) VALUES (19, 'War');
INSERT INTO GENRES (ID, NAME) VALUES (20, 'Sport');

INSERT INTO PEOPLE (ID, FIRST_NAME, LAST_NAME) VALUES (1, 'Steven', 'Spielberg');
INSERT INTO PEOPLE (ID, FIRST_NAME, LAST_NAME) VALUES (2, 'Christopher', 'Nolan');
INSERT INTO PEOPLE (ID, FIRST_NAME, LAST_NAME) VALUES (3, 'Quentin', 'Tarantino');
INSERT INTO PEOPLE (ID, FIRST_NAME, LAST_NAME) VALUES (4, 'Martin', 'Scorsese');
INSERT INTO PEOPLE (ID, FIRST_NAME, LAST_NAME) VALUES (5, 'Greta', 'Gerwig');
INSERT INTO PEOPLE (ID, FIRST_NAME, LAST_NAME) VALUES (6, 'James', 'Cameron');
INSERT INTO PEOPLE (ID, FIRST_NAME, LAST_NAME) VALUES (7, 'J.J.', 'Abrams');
INSERT INTO PEOPLE (ID, FIRST_NAME, LAST_NAME) VALUES (8, 'David', 'Fincher');
INSERT INTO PEOPLE (ID, FIRST_NAME, LAST_NAME) VALUES (9, 'Sofia', 'Coppola');
INSERT INTO PEOPLE (ID, FIRST_NAME, LAST_NAME) VALUES (10, 'Ridley', 'Scott');
INSERT INTO PEOPLE (ID, FIRST_NAME, LAST_NAME) VALUES (11, 'Tim', 'Burton');
INSERT INTO PEOPLE (ID, FIRST_NAME, LAST_NAME) VALUES (12, 'Peter', 'Jackson');
INSERT INTO PEOPLE (ID, FIRST_NAME, LAST_NAME) VALUES (13, 'David', 'Lynch');
INSERT INTO PEOPLE (ID, FIRST_NAME, LAST_NAME) VALUES (14, 'Wes', 'Anderson');
INSERT INTO PEOPLE (ID, FIRST_NAME, LAST_NAME) VALUES (15, 'Ridley', 'Scott');
INSERT INTO PEOPLE (ID, FIRST_NAME, LAST_NAME) VALUES (16, 'Danny', 'Boyle');
INSERT INTO PEOPLE (ID, FIRST_NAME, LAST_NAME) VALUES (17, 'Ang Lee', 'Lee');
INSERT INTO PEOPLE (ID, FIRST_NAME, LAST_NAME) VALUES (18, 'Cameron', 'Crowe');
INSERT INTO PEOPLE (ID, FIRST_NAME, LAST_NAME) VALUES (19, 'Ron', 'Howard');
INSERT INTO PEOPLE (ID, FIRST_NAME, LAST_NAME) VALUES (20, 'M. Night', 'Shyamalan');

INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (1, 'Jurassic Park', 'A theme park suffers a major power breakdown that allows its cloned dinosaur exhibits to run amok.', 1993);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (2, 'Inception', 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.', 2010);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (3, 'Pulp Fiction', 'The lives of two mob hitmen, a boxer, a gangster''s wife, and a pair of diner bandits intertwine in four tales of violence and redemption.', 1994);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (4, 'The Godfather', 'An organized crime dynasty''s aging patriarch transfers control of his clandestine empire to his reluctant son.', 1972);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (5, 'The Dark Knight', 'When the menace known as the Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham.', 2008);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (6, 'Forrest Gump', 'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold through the perspective of an Alabama man with an IQ of 75.', 1994);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (7, 'Fight Club', 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.', 1999);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (8, 'The Matrix', 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.', 1999);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (9, 'The Shawshank Redemption', 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.', 1994);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (10, 'Gladiator', 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.', 2000);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (11, 'Titanic', 'A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.', 1997);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (12, 'Avatar', 'A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.', 2009);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (13, 'The Silence of the Lambs', 'A young FBI cadet must confide in an incarcerated and manipulative killer to receive his help on catching another serial killer who skins his victims.', 1991);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (14, 'Saving Private Ryan', 'In the midst of World War II, a group of U.S. soldiers goes behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.', 1998);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (15, 'The Social Network', 'As Harvard students create the social networking site that would become known as Facebook, they must deal with both personal and legal issues that arise.', 2010);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (16, 'The Lion King', 'Lion prince Simba flees his kingdom after the death of his father, but returns as an adult to reclaim his throne.', 1994);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (17, 'Black Panther', 'T''Challa, the King of Wakanda, rises to the throne in the isolated, technologically advanced African nation, but his past comes back to haunt him.', 2018);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (18, 'Spider-Man: Homecoming', 'Peter Parker balances his life as an ordinary high school student in Queens with his superhero alter-ego Spider-Man, and faces the Vulture.', 2017);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (19, 'Wonder Woman', 'When an American pilot crashes on her sheltered island paradise and tells tales of a massive conflict raging outside, Diana leaves her home, convinced she can stop the threat.', 2017);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (20, 'Deadpool', 'A former special forces operative turned mercenary is subjected to a rogue experiment that leaves him with accelerated healing powers and a quest for revenge.', 2016);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (21, 'The Avengers', 'Earth''s mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity.', 2012);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (22, 'Guardians of the Galaxy', 'A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe.', 2014);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (23, 'Jurassic World', 'A new theme park, built on the original site of Jurassic Park, creates a genetically modified hybrid dinosaur that escapes containment and goes on a rampage.', 2015);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (24, 'Zootopia', 'In a city of anthropomorphic animals, a bunny cop and a cynical con artist fox must work together to uncover a conspiracy.', 2016);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (25, 'Inside Out', 'After young Riley is uprooted from her Midwest life and moved to San Francisco, her emotions—Joy, Fear, Anger, Disgust and Sadness—conflict on how best to navigate a new city, house, and school.', 2015);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (26, 'Coco', 'Aspiring musician Miguel, confronted with his family''s ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather, a legendary singer.', 2017);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (27, 'The Incredibles', 'A family of undercover superheroes, while trying to live the quiet suburban life, are forced into action to save the world.', 2004);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (28, 'Finding Nemo', 'After his son is captured in the Great Barrier Reef and taken to Sydney, a timid clownfish sets out on a journey to bring him home.', 2003);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (29, 'Shrek', 'An ogre''s peaceful life is shattered when numerous fairy tale characters are exiled to his swamp by the evil Lord Farquaad.', 2001);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (30, 'Toy Story', 'A cowboy doll is profoundly threatened and jealous when a new spaceman figure supplants him as top toy in a boy''s room.', 1995);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (31, 'The Lego Movie', 'An ordinary LEGO construction worker is mistakenly identified as the key to saving the world and is recruited to join a quest to stop an evil tyrant.', 2014);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (32, 'Moana', 'In Ancient Polynesia, when a terrible curse incurred by the Demigod Maui reaches the island of Motunui, Moana, the daughter of the island''s chief, answers the Ocean''s call to seek out the Demigod to set things right.', 2016);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (33, 'The Greatest Showman', 'Inspired by the story of P.T. Barnum''s creation of the circus and the lives of its star attractions.', 2017);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (34, 'La La Land', 'While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.', 2016);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (35, 'A Star is Born', 'A musician helps a young singer find fame as age and alcoholism send his own career into a downward spiral.', 2018);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (36, 'The Shape of Water', 'At a top secret research facility in the 1960s, a lonely janitor forms a unique relationship with an amphibious creature that is being held captive.', 2017);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (37, 'Get Out', 'A young African-American man visits his white girlfriend''s family estate, where he becomes ensnared in a more sinister real reason for the invitation.',  2017);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (38, 'Her', 'In a future where technology has advanced, a lonely writer develops an unlikely relationship with an operating system designed to meet his every need.', 2013);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (39, 'Moonlight', 'A timeless story of a young African-American man grappling with his identity and sexuality while growing up in a rough neighborhood of Miami.', 2016);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (40, 'The Florida Project', 'Set over one summer, the film follows a precocious six-year-old and her rebellious mother living in a budget motel near Disney World.', 2017);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (41, 'Lady Bird', 'In 2002, an artistically inclined seventeen-year-old girl comes of age in Sacramento, California.', 2017);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (42, 'The Favourite', 'In early 18th century England, a frail Queen Anne occupies the throne and her close friend, Lady Sarah, governs the country in her stead.', 2018);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (43, 'The Irishman', 'A mob hitman recalls his possible involvement with the slaying of Jimmy Hoffa.', 2019);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (44, 'Once Upon a Time in Hollywood', 'A faded television actor and his stunt double strive to achieve fame and success in the film industry during the final years of Hollywood'' s golden age in 1969 Los Angeles.', 2019);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (45, 'Parasite', 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.', 2019);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (46, 'Knives Out', 'A detective investigates the death of a patriarch of an eccentric, combative family.', 2019);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (47, '1917', 'As an infantry battalion assembles to wage war deep in enemy territory, two soldiers are assigned to race against time and deliver a message that will stop 1,600 men from walking straight into a deadly trap.', 2019);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (48, 'Soul', 'Joe Gardner, a middle-school band teacher, has a near-death experience and finds himself in the afterlife, where he learns about the true meaning of life.', 2020);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (49, 'Promising Young Woman', 'A young woman, traumatized by a tragic event in her past, seeks out vengeance against those who crossed her path.', 2020);
INSERT INTO MOVIES (ID, TITLE, DESCRIPTION, RELEASE_YEAR) VALUES (50, 'Dune', 'A noble family becomes embroiled in a war for control over the galaxy''s most valuable asset while its heir becomes troubled by visions of a dark future.', 2021);